### ISSUE TITLE
Agregar archivo .env.template

### ISSUE THREAD

**Issue by KatuGT** [joaquin-fuentes/proyectoFinalReactAdv#29]
Por buena practica recomiendo agregar este archivo .env.template  
El contenido de este archivo debería verse asi-

VITE_API_USUARIO =

VITE_API_MATERIA =

VITE_API_CURSO= 

VITE_API_NOVEDAD =

VITE_API_ASISTENCIA =

**Comment by joaquin-fuentes** [comment]
Ya se corrigió el problema mencionado. Si encuentra algún otro inconveniente, no dude en abrir un nuevo issue. Muchas gracias!
