### ISSUE TITLE
Sidebar mobile - Logo

### ISSUE THREAD

**Issue by KatuGT** [joaquin-fuentes/proyectoFinalReactAdv#30]
![image](https://github.com/user-attachments/assets/b552d456-f865-49de-bf9d-d688c29aa82c)

a la etiqueta <img> agreguemosle     object-fit: contain; para que no se deforme así

**Comment by joaquin-fuentes** [comment]
Ya se corrigió el problema mencionado. Si encuentra algún otro inconveniente, no dude en abrir un nuevo issue. Muchas gracias!
