### ISSUE TITLE
Alumno - Curso hardcodeado

### ISSUE THREAD

**Issue by KatuGT** [joaquin-fuentes/proyectoFinalReactAdv#31]
![image](https://github.com/user-attachments/assets/ae78368f-6ab7-4eae-a09e-c2a34d001059)

Es estatico el dato de "3° C", veamos de hacerlo dinámico como los demás :)

**Comment by joaquin-fuentes** [comment]
Ya se corrigió el problema mencionado. Si encuentra algún otro inconveniente, no dude en abrir un nuevo issue. Muchas gracias!
