### ISSUE TITLE
checkbox - mejora experiencia usuario

### ISSUE THREAD

**Issue by KatuGT** [joaquin-fuentes/proyectoFinalReactAdv#32]
![image](https://github.com/user-attachments/assets/402a96b0-446b-46fb-bfab-1191d5e96f3e)

Lo ideal es que al hacer click en la palabra "presente" se haga "check" en el input

actualmente solo si hago click en "cuadradito" se marca la asistencia
---------------

 para ello el label debe tener el atributo "for" que coincida con el "id" del input, averiguar como hacer esto con la librería que están usando

**Comment by joaquin-fuentes** [comment]
Ya se corrigió el problema mencionado. Si encuentra algún otro inconveniente, no dude en abrir un nuevo issue. Muchas gracias!
